# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'NewApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 好奇心

  target 'NewAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end
#pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'Alamofire'
pod 'SwiftyJSON'

end

